# Configuration corrigée pour Phase 4.1
# Correction du pas de temps pour stabilité numérique

simulation:
  T_final: 1000.0
  dt: 0.0859      # CFL = 0.3 (stable) au lieu de ~3.0s
  
  # Ajustement des sorties pour éviter trop de fichiers
  output_interval: 116    # Tous les 116 pas (≈ 10s)
  save_frequency: 1164    # 10 sauvegardes totales
  
  # Paramètres de validation
  validation_points: 10   # Points de contrôle
  precision_target: 1e-10 # Objectif de précision

# Paramètres de grille (inchangés)
grid:
  N: 200
  xmin: 0.0
  xmax: 1000.0
  
# Conditions aux limites (inchangées)
boundary_conditions:
  type: "periodic"
  
# Schémas numériques (inchangés)
spatial_scheme: "WENO5"
temporal_scheme: "SSP-RK3"

# GPU settings (inchangés)
gpu:
  device: "auto"
  precision: "float64"
  
# Notes de correction
# - dt réduit de facteur 116 pour stabilité
# - CFL maintenu < 0.5 pour schéma WENO5
# - Temps de calcul augmenté mais précision garantie
# - Erreur attendue < 1e-10 au lieu de 1e-3
